server:
  port: 8200
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///passport
    username: root
    password: 111
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jmx:
    enabled: false
  jpa:
    database: MYSQL
security:
  oauth2:
    client:
      client-id: jtodo
      client-secret: jtodo
logging:
  level:
    org:
      springframework: INFO
application:
  info:
    name: passport
    description: "Authentication server application that provides a unified login service for other applications"
    created: 2018-10-10
  protocol: http
  host: http://passport.wandan.site
  port: 8200