DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `account` VARCHAR(64) NOT NULL UNIQUE DEFAULT '',
  `password` CHAR(40) NOT NULL DEFAULT '',
  `nickname` VARCHAR(16) NOT NULL DEFAULT '',
  `avatar` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `temporary` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

$2a$10$X.Mjo5/08AKW5enKDpHOJuvA.H6iEN.pcfISUwY6/PuXtgnmTku5.