server:
  port: 8200
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///passport
    username: root
    password: 111
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jmx:
    enabled: false
  devtools:
    restart:
      additional-paths: src/main/java
      exclude: static/**, public/**
security:
  oauth2:
    client:
      client-id: jtodo
      client-secret: jtodo
application:
  info:
    name: passport
    description: "Authentication server application that provides a unified login service for other applications"
    created: 2018-10-10
  protocol: http
  host: http://passport.wandan.site
  port: 8200